
# Docker Image: server.js

# Node.js version
FROM node:12

# Create app directory
WORKDIR /docker

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm ci --only=production

# Bundle app source
COPY . .

# Bind express server port to Docker container port
EXPOSE 8010

# Command to start node server
CMD [ "node", "server.js" ]